language: julia

sudo: required

services:
  - docker

os:
  - linux
  - osx

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmpfi-dev

julia:
  - 0.5
  - 0.6
  - nightly

# matrix:
#   allow_failures:
#     - julia: 0.6
#     - julia: nightly

notifications:
  email: false

after_success:
- julia -e 'cd(Pkg.dir("MPFI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
